// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH-G6U0nvFJ0iET8lqUmbC3Zhfmv4LAG8',
    appId: '1:151666181556:web:111d60b1d5bdf53b091ee1',
    messagingSenderId: '151666181556',
    projectId: 'yougram-7db0b',
    authDomain: 'yougram-7db0b.firebaseapp.com',
    databaseURL: 'https://yougram-7db0b-default-rtdb.firebaseio.com',
    storageBucket: 'yougram-7db0b.appspot.com',
    measurementId: 'G-46NLE2G6DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGTcmmR3qgiX9ozHSiKL3DdLXW1zkQTs0',
    appId: '1:151666181556:android:ef869a60925c1b40091ee1',
    messagingSenderId: '151666181556',
    projectId: 'yougram-7db0b',
    databaseURL: 'https://yougram-7db0b-default-rtdb.firebaseio.com',
    storageBucket: 'yougram-7db0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFYCxby3h8zO_jADpDTSsGn1HTkUxqkU0',
    appId: '1:151666181556:ios:07ddb83fd9642576091ee1',
    messagingSenderId: '151666181556',
    projectId: 'yougram-7db0b',
    databaseURL: 'https://yougram-7db0b-default-rtdb.firebaseio.com',
    storageBucket: 'yougram-7db0b.appspot.com',
    iosClientId: '151666181556-c8mqjjtv0c7kpdmi9cnlcarl3pbsnms2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yougram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFYCxby3h8zO_jADpDTSsGn1HTkUxqkU0',
    appId: '1:151666181556:ios:07ddb83fd9642576091ee1',
    messagingSenderId: '151666181556',
    projectId: 'yougram-7db0b',
    databaseURL: 'https://yougram-7db0b-default-rtdb.firebaseio.com',
    storageBucket: 'yougram-7db0b.appspot.com',
    iosClientId: '151666181556-c8mqjjtv0c7kpdmi9cnlcarl3pbsnms2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yougram',
  );
}
