// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFL16fbJ8w55CQlaq-pSKGDIO1m_Zh3Vc',
    appId: '1:102066666482:web:d01afc27d1f0388f31096b',
    messagingSenderId: '102066666482',
    projectId: 'rescue-food-9d5c0',
    authDomain: 'rescue-food-9d5c0.firebaseapp.com',
    storageBucket: 'rescue-food-9d5c0.appspot.com',
    measurementId: 'G-W736R69CYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP8gCBlhkBnlnLRdre0oHc6OCOteoYP4M',
    appId: '1:102066666482:android:34e84ec46a5b5f9f31096b',
    messagingSenderId: '102066666482',
    projectId: 'rescue-food-9d5c0',
    storageBucket: 'rescue-food-9d5c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp_cGaqvKgWNcInqTON2_3eccT5gfwR8Y',
    appId: '1:102066666482:ios:d2567b87fa44e91e31096b',
    messagingSenderId: '102066666482',
    projectId: 'rescue-food-9d5c0',
    storageBucket: 'rescue-food-9d5c0.appspot.com',
    iosClientId: '102066666482-9f56oirk9rgooi24g6vkoi7b1c6v14r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yougram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp_cGaqvKgWNcInqTON2_3eccT5gfwR8Y',
    appId: '1:102066666482:ios:d2567b87fa44e91e31096b',
    messagingSenderId: '102066666482',
    projectId: 'rescue-food-9d5c0',
    storageBucket: 'rescue-food-9d5c0.appspot.com',
    iosClientId: '102066666482-9f56oirk9rgooi24g6vkoi7b1c6v14r2.apps.googleusercontent.com',
    iosBundleId: 'com.example.yougram',
  );
}
